### ISSUE TITLE
Incluir hierarquia nos metadados

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [AdaptaBrasil/AdaptaBIG#3]
Facilitar a organização dos metadados aproveitando a estrutura hierarquica do adaptabrasil.

**Comment by LukDeveloper** [comment]
Pelos meus testes está funcionando corretamente, o principal desafio foi na configuração do GeoNetwork e também na forma em que seriam exibidos os metadados.

![Screenshot 2024-11-18 at 12-01-42 Catálogo](https://github.com/user-attachments/assets/3597cf87-5599-45cf-85c3-aa06120c072b)

**Comment by pedro-andrade-inpe** [comment]
Está ótimo!
