### ISSUE TITLE
Título do dado no metadado

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [AdaptaBrasil/AdaptaBIG#4]
O título do dado no metadado não pode ser simplesmente o nome do indicador. Tem que seguir como sendo "AdaptaBrasil" seguido do nome do setor estratégico, seguido do risco (nível 2) seguido do nome do indicador. Se o indicador for de nível 2 não precisa repetir o nome duas vezes.

**Comment by LukDeveloper** [comment]
Obtive o seguinte resultado através do script:
Exemplo:
AdaptaBrasil: Impactos para Recursos Hídricos - Índice de Risco de Impacto para Seca - Índice de Ameaça Climática 

![Screenshot 2024-11-04 at 15-43-00 Catálogo](https://github.com/user-attachments/assets/763d315e-543a-4c91-a213-360f56519876)

**Comment by pedro-andrade-inpe** [comment]
@LukDeveloper a versao atual ja esta assim ou voce vai abrir um novo PR?

**Comment by LukDeveloper** [comment]
Identifiquei um bug, irei corrigi-lo antes de fazer o PR.

**Comment by LukDeveloper** [comment]
Realizei o PR. Caso esteja correta a proposta, irei utilizar a mesma lógica para criar a hierarquia dos metadados no GeoNetwork.
