### ISSUE TITLE
Inserção de overview provisória aos metadados

### ISSUE THREAD

**Issue by LukDeveloper** [AdaptaBrasil/AdaptaBIG#9]
Percebi que tem endereços de ícones nos indicadores de level 1 presentes na API. O que acham de utilizarmos eles como overviews provisórias para os metadados catalogados?

A ideia seria referenciar o ícone no próprio indicador e em seus respectivos filhos na hierarquia. 

Exemplo:

![Screenshot 2024](https://github.com/user-attachments/assets/3cd60113-1f30-48d3-a3a5-5fb20301feee)

![Screenshot 2024-11-19 at 13-54-45 Catálogo](https://github.com/user-attachments/assets/c305f99a-8f69-4c6f-b7d6-f073226dd922)

**Comment by pedro-andrade-inpe** [comment]
Está ótimo!
